### PR TITLE
Move to ISMRMRD 1.4.2.1

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
`DEVEL_BUILD=ON` are failing with 2 unrelated errors:
- https://github.com/SyneRBI/SIRF/issues/1019
-`test_load_SIMULATED_CONE_BEAM_DATA (test_dataexample.TestTestData)`  fails due to non-existent file (` /home/runner/install/share/cil/sim_cone_beam.nxs`)  https://github.com/SyneRBI/SIRF-SuperBuild/runs/4050142413?check_suite_focus=true#step:7:873. @paskino can you fix that one? 

However we will also have #568. We could conceivably set `siemens_to_ismrmrd` to https://github.com/ismrmrd/siemens_to_ismrmrd/pull/79, although it would be better to wait till they've merged that.

@ckolbPTB @johannesmayer @DANAJK do we have any test data for checking if we can safely upgrade `siemens_to_ismrmrd`?

**Comment by paskino** [comment]
@KrisThielemans @evgueni-ovtchinnikov I think the missing data from CIL is a transient problem as @gfardell was updating [CIL-Data ](https://github.com/TomographicImaging/CIL-Data) with the new data on 29/10/21, about the same time when you  opened this PR. 

CIL-Data is a submodule (hence [cloned by default by CMake](https://cmake.org/cmake/help/v3.10/module/ExternalProject.html)) of CIL and it is copied during the install phase in the install directory
https://github.com/SyneRBI/SIRF-SuperBuild/blob/4611d592199ebd271a55fbcfc41ad5198067822a/SuperBuild/External_CIL.cmake#L63

**Comment by KrisThielemans** [comment]
> @KrisThielemans @evgueni-ovtchinnikov I think the missing data from CIL is a transient problem as @gfardell was updating [CIL-Data ](https://github.com/TomographicImaging/CIL-Data) with the new data on 29/10/21, about the same time when you opened this PR.
> 
> CIL-Data is a submodule (hence [cloned by default by CMake](https://cmake.org/cmake/help/v3.10/module/ExternalProject.html)) of CIL and it is copied during the install phase in the install directory
> 
> https://github.com/SyneRBI/SIRF-SuperBuild/blob/4611d592199ebd271a55fbcfc41ad5198067822a/SuperBuild/External_CIL.cmake#L63

easy to check: re-run the workflow then

**Comment by DANAJK** [comment]
> `DEVEL_BUILD=ON` are failing with 2 unrelated errors:
> 
> * [CIL-wrapper test TestGradientMR_2D failures SIRF#1019](https://github.com/SyneRBI/SIRF/issues/1019)
>   -`test_load_SIMULATED_CONE_BEAM_DATA (test_dataexample.TestTestData)`  fails due to non-existent file (` /home/runner/install/share/cil/sim_cone_beam.nxs`)  https://github.com/SyneRBI/SIRF-SuperBuild/runs/4050142413?check_suite_focus=true#step:7:873. @paskino can you fix that one?
> 
> However we will also have #568. We could conceivably set `siemens_to_ismrmrd` to [ismrmrd/siemens_to_ismrmrd#79](https://github.com/ismrmrd/siemens_to_ismrmrd/pull/79), although it would be better to wait till they've merged that.
> 
> @ckolbPTB @johannesmayer @DANAJK do we have any test data for checking if we can safely upgrade `siemens_to_ismrmrd`?

Not sure how you test if there will be a problem with dependencies etc, other than trying it. If we can store the image output from a SIRF recon from Siemens data and compare the recon result from the same data after upgrading siemens_to_ismrmrd, that might provide an indication of any issues.

**Comment by KrisThielemans** [comment]
>  If we can store the image output from a SIRF recon from Siemens data and compare the recon result from the same data after upgrading siemens_to_ismrmrd, that might provide an indication of any issues.

not a bad idea. Do we have raw data somewhere? Maybe some of Claudia's data? Or the UCL calibration data (which is still in a bit of a mess...)

**Comment by DANAJK** [comment]
> not a bad idea. Do we have raw data somewhere? Maybe some of Claudia's data? Or the UCL calibration data (which is still in a bit of a mess...)

There is Siemens data, ISMRMRD file and SIRF recon already at: https://zenodo.org/record/3571228#.YX_3vC-l30o

**Comment by KrisThielemans** [comment]
> easy to check: re-run the workflow then

@paskino I reran the workflow. I'll leave it to you to check :-/

**Comment by paskino** [comment]
Apparently the problem is caused by the CIL submodule which points to an older commit. It should be fixed by https://github.com/TomographicImaging/CIL/pull/1043

**Comment by paskino** [comment]
Ubuntu 18.04 works fine, while something fails in ubuntu latest. Both seem to install numpy 1.18.

It seems the problem comes from the `dot_test`, which compares 2 arrays, but in practice it [compares the relative difference to 0 ](https://github.com/TomographicImaging/CIL/blob/fbd287bfc6b398090bb49b6d3f7a8461a96cd246/Wrappers/Python/cil/optimisation/operators/Operator.py#L202-L214)


https://github.com/TomographicImaging/CIL/issues/1044

**Comment by paskino** [comment]
@KrisThielemans @evgueni-ovtchinnikov the failure on this PR is due to a CIL unittest on SIRF objects that we are working on. https://github.com/TomographicImaging/CIL/pull/1048 

So I think that this PR can be safely merged, should you not want to wait until the bugfix upstream.

Notice that this bug shows up on Ubuntu latest (20.04) and not on 18.04, which is rather puzzling.

**Comment by KrisThielemans** [comment]
> Notice that this bug shows up on Ubuntu latest (20.04) and not on 18.04, which is rather puzzling.

not true. Travis docker failed which runs 18.04

**Comment by paskino** [comment]
Really? https://github.com/SyneRBI/SIRF-SuperBuild/pull/621/checks?check_run_id=4050142420 it says passed, no? Where's the failed test?

**Comment by KrisThielemans** [comment]
on master. https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/546535741#L16607

**Comment by KrisThielemans** [comment]
> > not a bad idea. Do we have raw data somewhere? Maybe some of Claudia's data? Or the UCL calibration data (which is still in a bit of a mess...)
> 
> There is Siemens data, ISMRMRD file and SIRF recon already at: https://zenodo.org/record/3571228#.YX_3vC-l30o

@DANAJK that's great. Unfortunately its [`recon.sh` ](https://zenodo.org/record/3571228/files/SIRF_recon.sh?download=1) is MacOS specific. (its `start_gadgetron` uses `pgrep` and `open`).  It currently also doesn't do any test on the final output. I'm not 100% sure how to run this kind of test as it runs the whole thing: `siemens_to_ismrmrd` + `gadgetron` + `SIRF`. Should we have a `SIRF/test/integration` directory where to put this?  Similar https://github.com/gadgetron/gadgetron/tree/master/test/integration

**Comment by paskino** [comment]
@epapoutsellis and I fixed the CIL/SIRF unittest and now you've it's all green. 
https://github.com/ismrmrd/siemens_to_ismrmrd/pull/79 has been merged.

@evgueni-ovtchinnikov @KrisThielemans I believe this can be safely merged now.

**Comment by KrisThielemans** [comment]
> @epapoutsellis and I fixed the CIL/SIRF unittest and now you've it's all green.

great. thanks! Sadly, our non-devel builds are still failing of course. see e.g. https://github.com/SyneRBI/SIRF-SuperBuild/runs/4109487470?check_suite_focus=true. Can we move the CIL commit?

**Comment by KrisThielemans** [comment]
hmmm. should have picked it up. I've re-run the workflow. Maybe it was just before you merged.

**Comment by KrisThielemans** [comment]
workflow succeeded this time. 👍

**Comment by paskino** [comment]
> Can we move the CIL commit?

We plan to release version 21.3 early next week.

**Pull request merged**
