### PR TITLE
switch default docker Python to miniconda3

### PR DESCRIPTION
**Pull request by KrisThielemans**
Use python3

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Only expected problem with NiftyPET I guess, due to #469

**Review by casperdcl — APPROVED** [review]
Sure. Regarding NiftyPET; should be easy to fix. Simply adding the cuda toolkit and then doing `pip install niftypet` would work fine, but as you say using the new `cmake` support (#469) may be required too for SIRF.

**Comment by KrisThielemans** [comment]
@casperdcl due to (y)our changes to reduce Travis overload, the `docker` jobs actually don't run on a PR (only `docker-core`), meaning that this PR is effectively not tested, see e.g.
https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/builds/220508500
and so we won't see problems like #505.
 
We could change the `.travis` temporarily, or just merge to `master` and see. What do you think would be best? (without creating a lot of work!)

**Comment by casperdcl** [comment]
I'd say mergig is fine - the docker images don't actually build any gpu stuff atm anyway (they only optionally comnect the gpu so users could install gpu code themselves).

**Pull request merged**
