### PR TITLE
PYTHON_DEST fixes

### PR DESCRIPTION
**Pull request by KrisThielemans**
fixes problem when PYTHON_DEST_DIR (or CMAKE_INSTALL_PREFIX?) isn't set

fixes https://github.com/SyneRBI/SIRF/issues/1020

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@paskino @evgueni-ovtchinnikov  can we merge this? I think it looks great 😄

**Comment by evgueni-ovtchinnikov** [comment]
same trouble persist on my VM, I am afraid:
[build_log.txt](https://github.com/SyneRBI/SIRF-SuperBuild/files/7485927/build_log.txt)
[make_log.txt](https://github.com/SyneRBI/SIRF-SuperBuild/files/7485930/make_log.txt)
[cmake_install.cmake.txt](https://github.com/SyneRBI/SIRF-SuperBuild/files/7485935/cmake_install.cmake.txt)

**Comment by KrisThielemans** [comment]
I don't understand, and will have a look later. I notice
```
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found PYTHON_EXECUTABLE=/usr/bin/python
-- Python version 2.7.18
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.10") 
-- Found PYTHON_INCLUDE_DIRS=/usr/include/python3.8
-- Found PYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.8.so
```
that's bound to give problems.

**Review by paskino — APPROVED** [review]
Looks fine to me. Significantly simplifies the code and it's all green!

**Comment by evgueni-ovtchinnikov** [comment]
changed `/usr/bin/python` to `/usr/bin/python3` manually in `ccmake` - now SIRF builds!

**Review by evgueni-ovtchinnikov — APPROVED** [review]
a comment on Python needed in the installation instructions

**Pull request merged**
