### PR TITLE
Bump cil tag

### PR DESCRIPTION
**Pull request by paskino**
updates to latest CIL release [21.0.0](https://github.com/vais-ral/CCPi-Framework/releases/tag/v21.0.0)

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Please merge `master` in here such that we can see Actions in action 😄

**Comment by paskino** [comment]
The failing CIL test needs investigating as it is running with numpy 1.20 and we've never tested it.

**Comment by paskino** [comment]
@KrisThielemans I fixed the failure in https://github.com/vais-ral/CCPi-Framework/pull/843 

So if that is the only failure, we will merge this PR.

**Comment by paskino** [comment]
Now that I disabled the `CIL_FRAMEWORK_TEST_6` this all works. However, current CIL master with the same unittest would [pass](https://github.com/SyneRBI/SIRF-SuperBuild/runs/2461523200?check_suite_focus=true)

I will reinstate the unittest after we've tagged CIL.

**Review by KrisThielemans — APPROVED** [review]

**Comment by KrisThielemans** [comment]
any reason to not run all tests with `CIL_LITE=ON`? The number of tests is proliferating quickly of course.

On the other hand, need to test full CIL?

**Comment by paskino** [comment]
Of course the requirements have changed in between this PR and now. I'll add `BUILD_CIL=ON` instead `BUILD_CIL_LITE=ON`

**Review by KrisThielemans — COMMENTED** [review]
sure, let's go with this for now

**Pull request merged**
