### PR TITLE
creates env_ccppetmr.* symbolic links

### LINKED ISSUE #418: env_ccppetmr.csh/.sh -> env_ccpsynerbi.csh/.sh
We still have `env_ccppetmr.csh.in/.sh.in` and still install `env_ccppetmr.csh/.sh`. Should be `env_ccpsynerbi.csh/.sh`.

### PR DESCRIPTION
**Pull request by paskino**
closes #418 

As discussed also in #481, we create the environment scripts with names `env_ccpsynerbi.sh` and `env_ccpsynerbi.csh` and  symbolic links `env_ccpsynerbi.sh` and `env_ccpsynerbi.csh` pointing to the former.

### CODE REVIEW

**Comment by paskino** [comment]
This requires `CMake >3.14`

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
Thanks, I' feel that bumping CMake to 3.14 for the sake of a link is probably too harsh. Can you instead check the CMake version, and make a copy of it's too old? sorry.

This PR will need a line in CHANGE.md and updates to our installation instructions as well.

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
Looks great. However, I think I prefer to call them `env_synerbi.*sh` , which is the name of the org. (Just looking ahead for when we're no longer a CCP...)

**Comment by paskino** [comment]
BTW why not `env_sirf.sh`? It would make more sense to me.

**Comment by KrisThielemans** [comment]
> BTW why not `env_sirf.sh`? It would make more sense to me.

to be discussed tomorrow. The SIRF-SuperBuild can be used to build STIR only (for instance)... confusing? sure

**Pull request merged**
