### PR TITLE
Add to LD_LIBRARY_PATH for MatlabEngine.so etc

### PR DESCRIPTION
**Pull request by rijobro**
Matlab libraries are in a funny place on Linux. They therefore need to be added to the LD_LIBRARY_PATH for SPM to be able to use them.

### CODE REVIEW

**Comment by rijobro** [comment]
Eric, could you try this? (not 100% sure of paths etc)

```
# go to superbuild
cd ~/devel/SIRF-SuperBuild
# check out this PR 
git remote add rijobro https://github.com/rijobro/SIRF-SuperBuild.git
git fetch rijobro
git checkout linux_matlab_fix
# Tell SIRF to use PR here: https://github.com/CCPPETMR/SIRF/pull/603
cd ~/devel/build
cmake . -DSIRF_URL:STRING=https://github.com/rijobro/SIRF.git -DSIRF_TAG:STRING=fix_matlab_linux -DDISABLE_MATLAB:BOOL=OFF
# make
make -j
# if successful, ctest
cd ~/devel/build/builds/SIRF/build
ctest -VV
```
Let me know if any steps fail.

**Comment by rijobro** [comment]
> I find it slightly scary to add Matlab stuff to LD_LIBRARY_PATH

I agree, but currently it seems it's either that or expecting the SIRF user to know to do it themselves.

**Comment by KrisThielemans** [comment]
could run into https://github.com/CCPPETMR/SIRF-SuperBuild/issues/257

**Comment by Ede1994** [comment]
I think it works now. The following tests failed:
`	  2 - MR_TESTS_PYTHON (Failed)
	  7 - SYN_TEST_CPLUSPLUS (Failed)
	  8 - SYN_TEST_PYTHON (Failed)
`
Another question: How can I add spm to Matlab?

**Comment by KrisThielemans** [comment]
Before we merge this, @Ede1994 can you paste the content of the `${Matlab_ROOT_DIR}/extern/bin/glnxa64` here? If there's versions of system/gcc files here, I wouldn't want to merge this PR.

**Comment by KrisThielemans** [comment]
@Ede1994 you can get output of tests by running with `ctest -VV` for instance. Adding SPM to your Matlab path would be by creating a `startup.m`, see e.g. https://uk.mathworks.com/help/matlab/ref/startup.html, or via the GUI.

These questions don't seem to belong in this PR though...

**Comment by Ede1994** [comment]
> Before we merge this, @Ede1994 can you paste the content of the `${Matlab_ROOT_DIR}/extern/bin/glnxa64` here? If there's versions of system/gcc files here, I wouldn't want to merge this PR.

returns:  `bash: /extern/bin/glnxa64: file or directory not found`

**Comment by rijobro** [comment]
@ede1994, you would need to do `ls <path/to/Matlab>/extern/bin/glnxa64`, where I think your computer, Matlab is installed in somewhere like `/usr/local/Matlab2019b`.

**Comment by KrisThielemans** [comment]
Sorry, you'll need to find out what M atlab_ROOT_DIR is. CMake should tell you.

**Comment by Ede1994** [comment]
okay. The content is:
`libMatlabDataArray.so  libMatlabEngine.so`

**Comment by KrisThielemans** [comment]
Only that? In that case, I'm happy to proceed, but still best to add a warning to our install instructions.

**Comment by rijobro** [comment]
Hold off merging this one. Seems unnecessary for my current build, not sure what I've changed.

**Pull request merged**
