### PR TITLE
Update to CIL 20.09

### PR DESCRIPTION
**Pull request by paskino**
This PR is meant to provide a build for CIL up to 20.09.
The idea here would be merge and tag this repo. 

Then I'd update for CIL >= 20.11

See #475

### CODE REVIEW

**Review by KrisThielemans — APPROVED** [review]
This is fine for me. Feel free to merge.

Up to you if in the next  PR you want to put some logic in that differentiates the install between different CIL versions.

Tagging strategy is a bit harder. Discussion elsewhere I guess.

**Comment by KrisThielemans** [comment]
I didn't check why Travis is failing

**Comment by paskino** [comment]
Travis fails because of CIL depends on [olefile ](https://github.com/vais-ral/CCPi-Framework/blob/v20.09.1/recipe/meta.yaml#L51)but it's not installed.

**Comment by paskino** [comment]
Travis fails because of a known bug in v2.2.0 in `divide` method.

Once the non CIL builds have finished I'd merge.

**Comment by KrisThielemans** [comment]
sure

**Comment by paskino** [comment]
For the record, this is the tag https://github.com/SyneRBI/SIRF-SuperBuild/tree/v2.2.0_CIL_20.09

**Pull request merged**
