### PR TITLE
install python-is-python3

### LINKED ISSUE #624: find_package(Cython) fails to find cython3
On my Ubuntu 20.04 (under WSL2, but I can't see how that matters) I have `cython3` (I could install `cython` which will give me a Python2 version), but surely don't want to).

Building with `BUILD_CIL_LITE=ON` gives
```
-- SuperBuild -     astra-python-wrapper => Requires astra-toolbox,
-- SuperBuild -       astra-toolbox => Requires Boost[INCLUDED],
-- SuperBuild -       astra-toolbox[OK]
CMake Error at SuperBuild/External_astra-toolbox.cmake:32 (message):
  astra-toolkit binding to Python depends on Cython
Call Stack (most recent call first):
  CMake/ExternalProjectDependency.cmake:593 (include)
  SuperBuild/External_astra-python-wrapper.cmake:29 (ExternalProject_Include_Dependencies)
  CMake/ExternalProjectDependency.cmake:593 (include)
  SuperBuild/External_CIL-ASTRA.cmake:28 (ExternalProject_Include_Dependencies)
  CMake/ExternalProjectDependency.cmake:593 (include)
  CMake/ExternalProjectDependency.cmake:639 (ExternalProject_Include_Dependencies)
  SuperBuild.cmake:331 (ExternalProject_Include_Dependencies)
  CMakeLists.txt:43 (include)
```
I can set `CYTHON_EXECUTABLE` to `/usr/bin/cython3`
https://github.com/SyneRBI/SIRF-SuperBuild/blob/053bfabcdfd0967873aaaf68252e7e0ef497cc26/CMake/FindCython.cmake#L11

However, this is probably unexpected for most people. Possibly even worse, it seems that if you have `cython` and its Python2, it'll find that one.

I see that this file comes from https://github.com/symengine/symengine.py/blob/master/cmake/FindCython.cmake which has moved on a bit. However, that one will first find `cython`, which again seems dangerous.

### PR DESCRIPTION
**Pull request by paskino**
closes #624

### CODE REVIEW

**Review by KrisThielemans — COMMENTED** [review]
I'm somewhat reluctant to do this. It's alright for docker or the VM, but we probably tell people they can execute these scripts if they want on their own system (I often do). This addition seems a bit surprising/dangerous in that situation.

If it solves a problem, then fine, let's merge this, but I'd like to see it documented, at least in the CHANGES

**Comment by paskino** [comment]
I don't think there is a bug per se. However, on Ubuntu 22.04 (our target release) you find, somewhat confusingly, `python3` and `cython`, but not `python` or `cython3`.

I had no problem both on docker and the VM. You reported #624 , for Ubuntu 20.04 which isn't supported.

Up to you if it makes sense to merge. To me it seems a bit more clear.

**Comment by KrisThielemans** [comment]
ok, if we have no problem now, then I wouldn't merge this. I wouldn't want our scripts messing up someone's Ubuntu...

**Comment by paskino** [comment]
They do already, IMHO, if they install all that stuff!

**Comment by KrisThielemans** [comment]
😀 at least, installing extra packages with `apt` shouldn't break anything.

anyway. if it isn't broken now, I wouldn't fix it!

**Pull request closed without merging**
