### PR TITLE
[GHA] test config with some USE_SYSTEM_*=OFF

### PR DESCRIPTION
**Pull request by KrisThielemans**
add a job where we self-build more stuff

### CODE REVIEW

**Comment by KrisThielemans** [comment]
This fails due to #644 #661 #662

**Comment by paskino** [comment]
Could you please update to the latest master after #656

**Comment by KrisThielemans** [comment]
sorry. this was already on latest `master` as far as I know

**Comment by paskino** [comment]
I think it is a problem of siemens_to_ismrmrd with Boost 1.78.

@KrisThielemans can you merge https://github.com/KrisThielemans/SIRF-SuperBuild/pull/2 ? It will probably make these builds green again.

**Comment by KrisThielemans** [comment]
2nd and 4th job failed at run-time due to #658. 3rd job due to #644

**Comment by KrisThielemans** [comment]
superseded by PRs from @paskino

**Pull request closed without merging**
