### PR TITLE
improve finding GTest

### LINKED ISSUE #126: GTEST_ROOT is not present if not building GTest
https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_GTest.cmake#L75 will not set `GTEST_ROOT` rather [`GTEST_LIBRARIES`](https://cmake.org/cmake/help/v3.11/module/FindGTest.html).

### PR DESCRIPTION
**Pull request by KrisThielemans**
GTest 1.11.0 exports CMake files, so attempt to use those by setting `GTest_DIR`, at least if CMake >= 3.20.

This should prevent problems on recent CMake:
- if `USE_SYSTEM_GTest=OFF`, it could find a system `GTestConfig.cmake` anyway, 
https://github.com/SyneRBI/SIRF-SuperBuild/issues/647#issuecomment-1042873509
- if it's `ON`, we didn't pass `GTest_DIR`

Fixes #126

### CODE REVIEW

**Comment by paskino** [comment]
Looks fine to me, however no GHA is building GTest. Should we add one?

**Comment by KrisThielemans** [comment]
you could have pushed to my branch, but anyway merged now.

**Comment by KrisThielemans** [comment]
feel free to merge when ok

**Comment by KrisThielemans** [comment]
Project maintainers can push to branches from PRs (unless disallowed by the PR creator)

**Pull request merged**
