### PR TITLE
use CMake 3.22 in docker scripts

### PR DESCRIPTION
**Pull request by KrisThielemans**
high time we upgrade CMake, but I suggest to merge this after 3.3

### CODE REVIEW

**Comment by paskino** [comment]
Just out of curiosity, do we need 3.23?

**Comment by KrisThielemans** [comment]
sure. we'll just use whatever is most recent then I guess.

**Comment by KrisThielemans** [comment]
This will likely fail on docker, see #769 and https://github.com/gschramm/parallelproj/issues/17

**Comment by KrisThielemans** [comment]
This PR is obselete. See #787

**Pull request closed without merging**
