### PR TITLE
Patch Gadgetron include files for RPE encoding

### PR DESCRIPTION
**Pull request by paskino**
Applies a patch to the installed Gadgetron include file `hoNFFT.h` that creates a compiler error in @johannesmayer [RPE-encoding](https://github.com/johannesmayer/SIRF/tree/rpe-encoding) branch.

### CODE REVIEW

**Comment by paskino** [comment]
Travis fails on all CIL tests as here we build SIRF 2.2.0 which had a bug in some algebra methods.

The other failure is due to a download error. 

I would merge.

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
Looks fine overall.

Did you test it works ok with the old Gadgetron (I can't see why not though).

I'm not super-excited to use Python for patching, but it seems it might be the most portable way of doing things. However, are you sure that 'PYTHON_EXECUTABLE` will be set if we switch `PYTHON` off (which is necessary for building MATLAB).

Finally, please include some doc in the `Gadgetron_include-patch.py` what it's doing, and ideally also a line in `CHANGES.md`

**Comment by paskino** [comment]
Of course I have used Python to patch because it'd be the most portable (in my mind of a Python dev).

The patch is applied to the version of Gadgetron [currently ](b6191eaaa72ccca6c6a5fe4c0fa3319694f512ab)built currenlty in the SuperBuild.

I'll add a test to check if `$PYTHON_EXECUTABLE` is available and if not look for it.

**Comment by KrisThielemans** [comment]
great. don't forget the documentation! Then merge.

**Comment by KrisThielemans** [comment]
could just as well fix the Codacy issue (trailing white space)
https://app.codacy.com/gh/SyneRBI/SIRF-SuperBuild/pullRequest?bid=22015540&prid=6876424&utm_campaign=new_commit&utm_medium=Email&utm_source=Internal&
before you press the button

**Pull request merged**
