### PR TITLE
correct .dockerignore file

### LINKED ISSUE #534: docker: run ./sirf-compose-server up -d sirf fails
Following the instructions in the [README ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/README.md#tldr-i-want-a-jupyter-notebook-service-now) (point 4) I type

```bash 
sirfuser@vagrant:~/devel/SIRF-SuperBuild/docker$ ./sirf-compose-server up -d sirf

[ ...  lots of output ...]

Step 43/60 : COPY devel/.ccache/ /opt/ccache/
ERROR: Service 'sirf' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat devel/.ccache/: file does not exist
```

However

```bash 

 sirfuser@vagrant:~/devel/SIRF-SuperBuild/docker$ stat devel/.ccache
  File: devel/.ccache
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 393745      Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1001/sirfuser)   Gid: ( 1001/sirfuser)
Access: 2021-05-11 09:41:27.851757421 +0000
Modify: 2021-05-11 09:41:27.851757421 +0000
Change: 2021-05-11 09:41:27.851757421 +0000
 Birth: -
```

Notice that the `sirfuser `must be in the `docker `group.

### PR DESCRIPTION
**Pull request by paskino**
closes #534

### CODE REVIEW

**Comment by KrisThielemans** [comment]
weird of course that you need this. As far as I understand, the `**` says "and all files in all subfolders". So, the question is after this PR, any content in `devel/.ccache` is actually put into the docker image (as expected). Can you please confirm that?

e.g. make test of the whole thing with a much shorter Dockerfile (reuse `core`, and then only other line in the `sirf` image is the `COPY`). create files in your `devel/.ccache/file` and `devel/.ccache/testdir/testfile` and build the image (should be really quick as it'll use the `core` that you have). Then check what is in the container after you start it.

**Comment by KrisThielemans** [comment]
oh, ideally try this in the VM as well, or even the old VM if you happen to still have it, as that's where I did my experiment (where everything worked fine). Here's what I have
```
$ docker --version
Docker version 18.09.7, build 2d0083d
```

**Comment by paskino** [comment]
I've created 2 files in `.ccache` and created an image. 

```bash
Step 48/48 : RUN find /opt/ccache
 ---> Running in 047bd3732493
/opt/ccache
/opt/ccache/testdir
/opt/ccache/testdir/testfile.edo
/opt/ccache/testfile.edo
```

Both files are where expected.

```bash
$ docker --version
Docker version 19.03.12, build 48a66213fe
```

**Comment by KrisThielemans** [comment]
don't forget the `[ci skip]'s to save some Travis time

**Pull request merged**
